name: Feature Request
description: Suggest a new feature for the project
type: Feature
body:
  - type: textarea
    attributes:
      label: The Problem
      description: What problem do you have, that this feature could resolve?
      placeholder: |
        For example:
        I cannot do ...
        I have to do ... every time.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Your Solution(s)
      description: How could ferium solve your problem?
      placeholder: |
        For example:
        Ferium should do ...
        Instead of doing ..., ferium should ... instead.
